#!/bin/bash

#login into private registry
npm login

npm publish ./dist/ngx-cdk/ --access=public

#logout when finished
npm logout
echo "Published successfully. Use 'npm install @rickzhou/ngx-cdk' in the project you want to use it."
